export const UNAUTHORIZED_ERROR_STATUS = 401;
export const UNAUTHORIZED_ERROR_MESSAGE = 'Unauthorized';

export const FORBIDDEN_ERROR_STATUS = 403;
export const FORBIDDEN_ERROR_MESSAGE = 'FORBIDDEN';
